### ISSUE TITLE
删除第M组的第N项

### ISSUE THREAD

**Issue by VictorChow** [Loren1994/UniversalTypeRecyclerView#1]
数据里删除第M组的第N项后，如何用UniversalAdapter通知？

**Comment by Loren1994** [comment]
使用adapter.removeIndex(parentIndex: Int, childIndex: Int)
具体见:https://github.com/Loren1994/UniversalTypeRecyclerView/blob/master/app/src/main/java/loren/pers/universalrecyclerview/sample/CustomerAdapter.kt

**Comment by VictorChow** [comment]
thanks
